name: Build

on:
  push:
    branches: master
    paths:
    - 'code/**'
    - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile all C++ files
        run: ./tests/buildall.sh
