name: Compiler and Upload Document
on:
  push:
    branches: master
    paths:
    - 'document/**'
    - '.github/workflows/document.yml'


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_lualatex: true
          work_in_root_file_dir: true
          root_file: document/main.tex
      - name: Copy PDFs
        run: |
          mkdir public
          cp ./document/*.pdf ./public
      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: Documents
          path: public/*.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: doc
          enable_jekyll: true
