name: Document

on: push

jobs:
  document:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Document
        run: docker run -v "${PWD}:/src" -w /src thomasweise/docker-texlive-full latexmk -pdf -latexoption="-shell-escape" main.tex

      - uses: actions/upload-artifact@v2
        with:
          name: document.pdf
          path: main.pdf
