name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile all C++ files
        run: ./tests/buildall.sh

  verify:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: oj-verify run

  document:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Document
        run: docker run -v "${PWD}:/src" -w /src thomasweise/docker-texlive-full latexmk -pdf -latexoption="-shell-escape" main.tex

      - uses: actions/upload-artifact@v2
        with:
          name: document.pdf
          path: src/main.pdf
