name: verify

on:
  push:
    branches: master
    paths:
    - 'code/**'
    - 'tests/**'
    - '.github/workflows/verify.yml'

jobs:
  verify:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: oj-verify all
